[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[workspace]
resolver = "1"
members = [
    "ws2812-avr",
    "examples/rainbow",
    "examples/custom-timings"
]
